# Generated by Django 4.1.1 on 2022-10-03 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0077_alter_revision_user'),
        ('generic', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Generic',
            new_name='GenericPage',
        ),
    ]
