# Generated by Django 4.1.1 on 2022-10-03 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0002_rename_generic_genericpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericpage',
            name='body',
        ),
    ]
