# Generated by Django 4.1.1 on 2022-10-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0008_genericpage_author_alter_genericpage_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='company_name',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
