# Generated by Django 4.1.1 on 2022-10-03 07:16

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0009_alter_author_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='company_name',
            field=wagtail.fields.RichTextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='genericpage',
            name='introduction',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
