# Generated by Django 4.1.1 on 2022-10-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0010_alter_author_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='genericpage',
            name='introduction',
            field=models.TextField(blank=True),
        ),
    ]
