# Generated by Django 4.1.1 on 2022-10-03 02:08

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_body_alter_homepage_banner_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='Footer',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
