# Generated by Django 4.1.1 on 2022-10-03 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_footer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='Footer',
        ),
    ]
